name: Release package

on:
  push:
    branches:
      [beta, main, alpha, 3.x.x, 3.x, 1.x, 1.x.x next, next-major]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run generateFiles

      - name: Publish
        run: yarn run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
