name: Run tests

# Trigger the workflow on pull request or manually
on: [pull_request, workflow_dispatch]

jobs:
  run_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check-out repository
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Run jest
      - name: Run tests
        run: yarn test:once
